version: "3.7"

services:
  node:
    container_name: node_server
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - mongo
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - .:/app
    command: npm start
    networks:
      - common

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - ${DB_LC_PORT}:27017
    volumes:
      - ./data:/data/db
    networks:
      - common

networks:
  common:
