version: "3.7"
services: 
  backend:
    build: .
    ports: 
      - "3300:3300"
    depends_on:
      - mongo
  mongo:
    build: ./database
  frontend:
    build: ../
    ports:
      - "8080:80"
    depends_on:
      - backend